"""Streamlit dashboard: live quote + Gemini VC risk assessment."""

from __future__ import annotations

from datetime import datetime, timezone

import streamlit as st
from fpdf import FPDF


from market_check import get_current_quote
from vc_agent import DEFAULT_MODEL, VCAssessment, assess_risk_sync


def _safe_pdf_text(text: str) -> str:
    """ASCII-safe text for core Helvetica (avoid encoding errors)."""
    return text.encode("latin-1", "replace").decode("latin-1")


def create_pdf(ticker: str, price: float, assessment: VCAssessment) -> bytes:
    """Build a VC-style investment memo PDF (may span multiple pages if content is long)."""

    LINE_H = 8

    # Brand palette
    HEADER_BLUE = (0, 48, 87)
    FOOTER_GRAY = (110, 110, 110)
    RISK_LOW = (12, 122, 62)
    RISK_HIGH = (193, 42, 42)
    HEADER_BAR_H = 24.0
    BULLET_INDENT = 8.0

    class InvestmentMemoPDF(FPDF):
        def __init__(self) -> None:
            super().__init__()
            self._generated_at = datetime.now(timezone.utc)
            self.set_margins(18, 18, 18)

        def footer(self) -> None:
            self.set_y(-14)
            self.set_text_color(*FOOTER_GRAY)
            self.set_font("Helvetica", style="", size=7)
            ts = self._generated_at.strftime("%Y-%m-%d %H:%M:%S UTC")
            line = _safe_pdf_text(f"{ts} | Generated by Autonomous-VC Agent")
            self.multi_cell(0, LINE_H, line, align="C")
            self.ln()
            self.set_text_color(0, 0, 0)

    def hrule(pdf: FPDF) -> None:
        pdf.set_draw_color(55, 55, 55)
        y = pdf.get_y()
        pdf.line(pdf.l_margin, y, pdf.l_margin + pdf.epw, y)
        pdf.set_draw_color(0, 0, 0)
        pdf.ln(5)

    sym = ticker.strip().upper()
    pdf = InvestmentMemoPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    bullet_left = pdf.l_margin + BULLET_INDENT

    # --- Header bar (edge-to-edge) ---
    pdf.set_fill_color(*HEADER_BLUE)
    pdf.rect(0, 0, pdf.w, HEADER_BAR_H, "F")
    pdf.set_xy(pdf.l_margin, 8)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", style="B", size=18)
    pdf.multi_cell(0, LINE_H, _safe_pdf_text(f"CONFIDENTIAL: AI Investment Memo - {sym}"), align="C")
    pdf.ln()
    pdf.set_text_color(0, 0, 0)

    # Body starts below bar
    pdf.set_y(HEADER_BAR_H + 10)

    pdf.set_font("Helvetica", style="B", size=12)
    pdf.multi_cell(0, LINE_H, _safe_pdf_text("Executive Summary"))
    pdf.ln()
    pdf.set_font("Helvetica", size=11)
    pdf.multi_cell(0, LINE_H, _safe_pdf_text(f"Price: {price:,.2f}"))
    pdf.ln()
    risk = assessment.risk_assessment
    if risk == "Low":
        pdf.set_text_color(*RISK_LOW)
    elif risk == "High":
        pdf.set_text_color(*RISK_HIGH)
    else:
        pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", style="B", size=11)
    pdf.multi_cell(0, LINE_H, _safe_pdf_text(f"Risk verdict: {risk}"))
    pdf.ln()
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", size=11)
    pdf.multi_cell(0, LINE_H, _safe_pdf_text(f"News sentiment: {assessment.news_sentiment}"))
    pdf.ln()

    hrule(pdf)

    pdf.set_font("Helvetica", style="B", size=12)
    pdf.multi_cell(0, LINE_H, _safe_pdf_text("Analysis"))
    pdf.ln()
    pdf.set_font("Helvetica", size=11)
    pdf.multi_cell(0, LINE_H, _safe_pdf_text(assessment.recommendation))
    pdf.ln()

    hrule(pdf)

    pdf.set_font("Helvetica", style="B", size=12)
    pdf.multi_cell(0, LINE_H, _safe_pdf_text("Recent News"))
    pdf.ln()
    pdf.set_font("Helvetica", size=11)
    if assessment.key_headlines:
        for headline in assessment.key_headlines:
            pdf.set_x(bullet_left)
            pdf.multi_cell(0, LINE_H, _safe_pdf_text(f"- {headline}"))
            pdf.ln()
    else:
        pdf.set_x(bullet_left)
        pdf.multi_cell(0, LINE_H, _safe_pdf_text("No headlines returned."))
        pdf.ln()

    return bytes(pdf.output())


def _display_model_name() -> str:
    """Human-readable Gemini model id for the sidebar."""
    if DEFAULT_MODEL.startswith("google-gla:"):
        return DEFAULT_MODEL.split(":", maxsplit=1)[1]
    return DEFAULT_MODEL


def _render_sidebar() -> None:
    with st.sidebar:
        st.header("System Status")
        st.caption("Gemini model")
        st.code(_display_model_name(), language=None)
        snap_dl = st.session_state.get("snapshot")
        if snap_dl is not None:
            st.divider()
            pdf_bytes = create_pdf(
                snap_dl["ticker"],
                snap_dl["price"],
                snap_dl["assessment"],
            )
            st.download_button(
                label="📥 Download VC Memo (PDF)",
                data=pdf_bytes,
                file_name=f"VC_Memo_{snap_dl['ticker']}.pdf",
                mime="application/pdf",
                use_container_width=True,
            )


def main() -> None:
    st.set_page_config(
        page_title="Autonomous VC: AI Market Analyst",
        page_icon="📊",
        layout="wide",
    )

    st.title("Autonomous VC: AI Market Analyst")

    col_input, col_btn = st.columns([4, 1])
    with col_input:
        ticker_raw = st.text_input(
            "Stock ticker",
            value="NVDA",
            placeholder="e.g. NVDA",
            help="US ticker symbol (yfinance).",
        )
    with col_btn:
        analyze = st.button("Analyze", type="primary", use_container_width=True)

    ticker = (ticker_raw or "NVDA").strip().upper()
    if not ticker:
        st.warning("Enter a ticker symbol.")
        _render_sidebar()
        return

    run = analyze or "snapshot" not in st.session_state
    if run:
        try:
            price, currency = get_current_quote(ticker)
        except Exception as e:
            st.error(f"Could not fetch market data for **{ticker}**: {e}")
            _render_sidebar()
            return

        try:
            with st.spinner("Researcher is browsing the web..."):
                assessment = assess_risk_sync(ticker, price)
        except RuntimeError as e:
            st.error(str(e))
            _render_sidebar()
            return
        except Exception as e:
            st.error(f"Risk assessment failed: {e}")
            _render_sidebar()
            return

        st.session_state.snapshot = {
            "ticker": ticker,
            "price": price,
            "currency": currency,
            "assessment": assessment,
        }
    else:
        snap = st.session_state.snapshot
        if snap["ticker"] != ticker:
            st.caption(f"Showing results for **{snap['ticker']}**. Click **Analyze** to refresh for **{ticker}**.")
        price = snap["price"]
        currency = snap["currency"]
        assessment = snap["assessment"]

    _render_sidebar()

    m_col1, m_col2 = st.columns(2)
    with m_col1:
        st.metric(
            label=f"{st.session_state.snapshot['ticker']} — last price ({currency})",
            value=f"{price:,.2f}",
        )
    with m_col2:
        st.metric(
            label="News sentiment",
            value=assessment.news_sentiment,
        )

    st.subheader("Verdict")
    risk = assessment.risk_assessment
    verdict_body = f"**Risk:** {risk}\n\n{assessment.recommendation}"
    if risk == "Low":
        st.success(verdict_body)
    elif risk == "Medium":
        st.warning(verdict_body)
    else:
        st.error(verdict_body)

    with st.expander("AI Research Headlines", expanded=False):
        if assessment.key_headlines:
            for line in assessment.key_headlines:
                st.markdown(f"- {line}")
        else:
            st.caption("No headlines returned.")


if __name__ == "__main__":
    main()
